name: blog deploy

on: 
  push:
    branches: 
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - run: npm ci
    - run: npm install vuepress
    - run: npm run build
    - run: cp CNAME docs/.vuepress/dist/
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@master
      env:
        ACTIONS_DEPLOY_KEY: ${{secrets.blog}}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: docs/.vuepress/dist
